name: CI - Lib

on:
  pull_request:
  push:
    branches:
      - main

jobs:
  ci-lib:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@08eba0b27e820071cde6df949e0beb9ba4906955 # v4
      - run: corepack enable
      - uses: actions/setup-node@v4
        with:
          node-version: 22
          corepack: true
          cache: pnpm

      - name: Install dependencies
        run: pnpm i

      - name: Run linters
        run: pnpm lint

      - name: Type check
        run: pnpm typecheck

      - name: Run unit test
        run: pnpm test

      - name: Build the lib
        run: pnpm build
