name: CI - Lib

on:
  pull_request:
  push:
    branches:
      - main

jobs:
  ci-lib:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@08eba0b27e820071cde6df949e0beb9ba4906955 # v4

      - name: Install pnpm
        uses: pnpm/action-setup@a7487c7e89a18df4991f7f222e4898a00d66ddda # v4

      - uses: actions/setup-node@a0853c24544627f65ddf259abe73b1d18a591444 # v5
        with:
          node-version: 22
          cache: pnpm

      - name: Install dependencies
        run: pnpm i

      - name: Run linters
        run: pnpm lint

      - name: Type check
        run: pnpm typecheck

      - name: Run unit test
        run: pnpm test

      - name: Build the lib
        run: pnpm build
